language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      mono: latest
      dotnet: 2.2.105

    - os: osx
      osx_image: xcode10.1
      mono: latest
      dotnet: 2.2.105

    - os: windows
      mono: none

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - dotnet --info
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://download.mono-project.com/repo/ubuntu beta-xenial main" | sudo tee /etc/apt/sources.list.d/mono-xamarin-beta.list; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get  --yes --allow-unauthenticated upgrade mono-complete; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mono --version; fi

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget --retry-connrefused --waitretry=1 -O /tmp/mdk.pkg http://download.mono-project.com/archive/5.18.0/macos-10-universal/MonoFramework-MDK-5.18.0.225.macos10.xamarin.universal.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg /tmp/mdk.pkg -target /; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/bin/mono --version; fi

#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install mono; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install dotnetcore-sdk  --ignore-dependencies; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet --info; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install nuget.commandline; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build.sh --verbosity diagnostic; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh --verbosity diagnostic; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Get-ExecutionPolicy -List; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell Set-ExecutionPolicy RemoteSigned -Scope LocalMachine; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell ./build.ps1; fi

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine

notifications:
  email:
    recipients:
      - wangtianjiao.wang959@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
